[project]
name = "rafo"
authors = [
    {name = "Irvin Hostettler, ALEX Berlin", email = "hostettler@alex-berlin.de"}
]
description = "Collect files and metadata for a radio show uses NocoDB as backend"
version = "0.1.0"
dependencies = [
    "click",
    "dynaconf",    
    "fastapi",    
    "ffmpeg-python",    
    "Jinja2",    
    "nocodb",    
]